---
# tasks file for flask_web
    - name: Install Python Flask
      pip:
        name: ['flask', 'flask-mysql']
        state: present

    - name: Copy App Source Code
      copy:
        src: ./simple-webapp/app.py
        dest: /opt/app.py

    - name: Start Web Server
      shell: nohup /usr/local/bin/flask run --host=0.0.0.0 &
      environment:
        FLASK_APP: /opt/app.py